//**********************************************************************
//    CopyRight  (c)  Shenzhen Saiyuan Microelectronics Co., Ltd
//    File Name   :   CompCtrlDefine.h
//    Function    :   Store composite control define
//    Version     :   V3.2.0
//    Date        :   2022.02.16
///*********************************************************************
#ifndef COMP_CTRL_DEFINE_H
    #define COMP_CTRL_DEFINE_H
#endif	

/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
