///**********************************************************************/
//    CopyRight  (c)  Shenzhen Saiyuan Microelectronics Co., Ltd
//    File Name   :   SC_itExtern.h
//    Function    :   store extern var code
//    Version     :   V3.2.0
//    Date        :   2022.02.16
///**********************************************************************/
#ifndef SC_IT_EXTERN_H
    #define SC_IT_EXTERN_H
#include "HeadFiles\SysFunVarDefine.h"
#endif

/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
