//**********************************************************************
//    CopyRight  (c)  Shenzhen Saiyuan Microelectronics Co., Ltd
//    File Name   :   SysFunVarDefine.h
//    Function    :   Store var control and function control extern
//    Version     :   V3.2.0
//    Date        :   2022.02.16
//**********************************************************************
#ifndef SYS_FUN_VAR_DEFINE
    #define SYS_FUN_VAR_DEFINE
#include "HeadFiles\CustomType.h"
#include "HeadFiles\UserExport.h"
#include "HeadFiles\FunctionType.h"
#include "HeadFiles\CompCtrlDefine.h"
#endif

/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/

