//**********************************************************************
//    CopyRight  (c)  Shenzhen Saiyuan Microelectronics Co., Ltd
//    File Name   :   CustomType.h
//    Function    :   
//    Version     :   V3.2.0
//    Date        :   2022.02.16
//**********************************************************************
/***********************user_code_area*********************/
/*<UserCodeStart>*/
/*<UserCodeEnd>*/
/**********************.user_code_area.********************/
#ifndef CUSTOM_TYPE_H
    #define CUSTOM_TYPE_H
#endif	
/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
