//**********************************************************************
//    CopyRight  (c)  Shenzhen Saiyuan Microelectronics Co., Ltd
//    File Name   :   Function.h
//    Function    :   Store quote of the function 
//    Version     :   V3.2.0
//    Date        :   2022.02.16
//**********************************************************************
/***********************user_code_area*********************/
/*<UserCodeStart>*/
/*<UserCodeEnd>*/
/**********************.user_code_area.********************/
#ifndef FUNCTION_H
    #define FUNCTION_H
#endif	
/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
