//**********************************************************************
//    CopyRight  (c)  
//    File Name   :   CompCtrlDefine.C
//    Function    :   Store composite control define
//    Version     :   V3.2.0
//    Date        :   2022.02.16
///*********************************************************************
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
