//**********************************************************************
//    CopyRight  (c) 
//    File Name   :   SysFunVarDefine.c
//    Function    :   Store var control and function control define
//    Version     :   V2.0
//    Date        :   2021.04.08
//**********************************************************************
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
//**********************************************************************
/**************************************Generated by EasyCodeCube*************************************/

/*************************************.Generated by EasyCodeCube.************************************/
